// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFINHFejwetCKPkUququ_lou_L7buOp0',
    appId: '1:457124736555:web:82e7ee101bb191e269846e',
    messagingSenderId: '457124736555',
    projectId: 'firbase-auth-bloc',
    authDomain: 'firbase-auth-bloc.firebaseapp.com',
    storageBucket: 'firbase-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5euPqd1Oz14YBVVUrnaX8sNBLwDk3UkQ',
    appId: '1:457124736555:android:88572c87ccde969269846e',
    messagingSenderId: '457124736555',
    projectId: 'firbase-auth-bloc',
    storageBucket: 'firbase-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xT4g0y9KStQjKEi0yU-2oUJAmREkw2o',
    appId: '1:457124736555:ios:04631157e81567d669846e',
    messagingSenderId: '457124736555',
    projectId: 'firbase-auth-bloc',
    storageBucket: 'firbase-auth-bloc.appspot.com',
    iosBundleId: 'com.example.firebaseAuthAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xT4g0y9KStQjKEi0yU-2oUJAmREkw2o',
    appId: '1:457124736555:ios:04631157e81567d669846e',
    messagingSenderId: '457124736555',
    projectId: 'firbase-auth-bloc',
    storageBucket: 'firbase-auth-bloc.appspot.com',
    iosBundleId: 'com.example.firebaseAuthAppBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeFINHFejwetCKPkUququ_lou_L7buOp0',
    appId: '1:457124736555:web:fe701fdfefdce5a969846e',
    messagingSenderId: '457124736555',
    projectId: 'firbase-auth-bloc',
    authDomain: 'firbase-auth-bloc.firebaseapp.com',
    storageBucket: 'firbase-auth-bloc.appspot.com',
  );
}
